name: Deploy to Test

on:
  push:
    branches: [ main ]
    paths:
      - 'arm-templates/**'
      - '.github/workflows/deploy-test.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Validate ARM Templates
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-multi-env-test
          template: ./arm-templates/main.json
          parameters: ./arm-templates/parameters.test.json
          deploymentMode: Validate
          
  deploy:
    needs: validate
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy ARM Templates
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-multi-env-test
          template: ./arm-templates/main.json
          parameters: ./arm-templates/parameters.test.json
          deploymentMode: Incremental