name: Deploy to Development

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'arm-templates/**'
      - '.github/workflows/deploy-dev.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Validate ARM Templates
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-multi-env-dev
          template: ./arm-templates/main.json
          parameters: ./arm-templates/parameters.dev.json
          deploymentMode: Validate
          
  deploy:
    needs: validate
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy ARM Templates
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-multi-env-dev
          template: ./arm-templates/main.json
          parameters: ./arm-templates/parameters.dev.json
          deploymentMode: Incremental
          deploymentName: GitHubActionDeployment
          additionalArguments: --template-specs-folder ./arm-templates